toolsConfig:
  decompilers: jadx
  analysisTools:
    - taie
    - semgrep
    - permissionChecker
    - truffleHog
  llmProvider: copilot                           # supports openai, anthropic, copilot and gemini
  llmApiKey: Bearer YOUR_API_KEY                # Add token with scheme if applicable (e.g. Bearer) otherwise just the token. n/a for copilot
  llmModel: gpt-5.6-sol                               # Model to use for LLM analysis as per the provider
  llmBaseUrl: https://api.openai.com            # URL for your LLM provider API, n/a for copilot
  taiEAgentEnabled: false                       # flip to true if you reach input token limit in direct flow or else keep it false
  agentLlmApiKey: Bearer YOUR_AGENT_API_KEY     # Used only by TaiE agent mode
  agentLlmModel: gpt-4                          # Used only by TaiE agent mode
  agentLlmBaseUrl: https://api.openai.com       # Used only by TaiE agent mode
  taiEAgentMaxToolResponsePercentage: 30        # Max context % for agent tool responses
  taiEMaxHeapGb: 0                              # Specify heap size here, defaults to 75% of available memory if 0
  taiEOnlyApp: true                             # true = taint analysis only app code including everything bundled into it sdk etc. ; false = whole-program including reading their bodies as well
  ignoredTaiePackages:                          # package prefix for tai-e to exclude from triage being either third party or false positives
    - "com.example.thirdparty."
    - "com.yourorg.analytics."
  ignoredSemgrepPackages:                       # package prefix for semgrep to exclude from triage being either third party or false positives
    - "com.false.positives."

pathConfigs:
  baseDirectory: BASE_DIRECTORY_FOR_PROJECT     # Replace this with your base directory path for thorfinn
  decompiledApkPath: /resources/decompiled_apks/
  taiePath: /resources/tools/tai-e-all-0.5.4-SNAPSHOT.jar
  androidPlatformsPath: /resources/android-platforms/
  taieOutputPath: /resources/taie_output/
  taintConfigPath: /config/taint_config.yml
  permissionCheckerPath: /resources/tools/permissionChecker.py
  semgrepRulesPath: /resources/tools/semgrep-rules/
  outputPath: /resources/output/
  cvssConfigPath: /config/cvss_config.yml

